# docker-compose
# author: dreamlu
# github.com/dreamlu
version: '3'
services:
  # mysql-server
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/dreamlu/mysql:8.0
    #command:
    #privileged: true
    container_name: d-mysql
    environment:
      MYSQL_DATABASE: deercoder-gin
      MYSQL_USER: dreamlu
      MYSQL_PASSWORD: dreamlu
      MYSQL_ROOT_PASSWORD: dreamlu
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - 3308:3306
    restart: always
    # sql备份目录
    volumes:
      - /root/demo/bak/mysql/data:/var/lib/mysql
    networks:
      - demo
  # redis
  redis:
    image: redis:4.0
    ports:
      - 6378:6379
    container_name: d-redis
    restart: always
  # api gateway
  demo:
    image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:deercoder-gin
    ports:
      - 9000:9000
    container_name: d-demo
    restart: always
    volumes:
      - /root/bak/static:/static
    networks:
      - demo

networks:
  demo:
    driver: bridge