apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - name: "8009"
    port: 8009
    targetPort: 8009
    #nodePort: 30009
  selector:
    app: api-gateway
  #type: NodePort
