apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server2
  name: eureka-server2
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
    nodePort: 30762
  selector:
    app: eureka-server2
  type: NodePort
