apiVersion: v1
kind: PersistentVolume  #资源类型
metadata:
  name: nfs-static
  labels:
    name: nfs-static
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany  #访问模式，多个客户端读写
  # persistentVolumeReclaimPolicy: Recycle #回收策略-可以回收
  nfs:
    path: "/root/yhf/data/static" # 目录必须存在
    server: 172.17.0.17 # 192.168.31.105 #k8s-nfs matser
    readOnly: false  #只读

---
apiVersion: v1
kind: PersistentVolume  #资源类型
metadata:
  name: nfs-log
  labels:
    name: nfs-log
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  #访问模式，多个客户端读写
  # persistentVolumeReclaimPolicy: Recycle #回收策略-可以回收
  nfs:
    path: "/root/yhf/data/log" # 目录必须存在
    server: 172.17.0.17 # 192.168.31.105 #k8s-nfs matser
    readOnly: false  #只读