apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      # 反亲和性
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - eureka-server
      containers:
        - image: redis:4.0
          name: w-redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis