# docker-compose
# author: dreamlu
# github.com/dreamlu
version: '3'
services:
  # mysql 连接
  # mysql-server
  mysql:
    image: mysql:5.7
    #command:
    #privileged: true
    container_name: w-mysql
    #image: mysql/mysql-server:5.7
    #image: mysql:5.7
    environment:
      MYSQL_DATABASE: xmd
      MYSQL_USER: dreamlu
      MYSQL_PASSWORD: wobangkj
      MYSQL_ROOT_PASSWORD: wobangkj
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - 3308:3306
    restart: always

  # 举例如下
  # staff service
  staff-service:
    image: registry.cn-hangzhou.aliyuncs.com/deercoder/dreamlu:xmd-staff-service
    ports:
      - 8767:8767
    container_name: w-staff
    restart: always