groups:
  - name: should_fire
    rules:
      - alert: HighPercentageError
        expr: |
          sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
            /
          sum(rate({app="foo", env="production"}[5m])) by (job)
            > 0.05
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latency
  - name: my_test
    rules:
      - alert: my_test
        annotations:
          message: "my alert test."
        expr: '{job="varlogs"} |= "status"'
        for: 1m
        labels:
          severity: critical