groups:
  - name: should_fire
    rules:
      - alert: HighPercentageError
        expr: |
          sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
            /
          sum(rate({app="foo", env="production"}[5m])) by (job)
            > 0.05
        for: 10m
        annotations:
          summary: High request latency
  - name: my_test
    rules:
      - alert: my_test
        annotations:
          message: "my alert test."
        # 10分钟内出现status则告警,不能太短,因为告警计算流程(normal->pending->firing)也要时间(或许可以配置)
        expr: |
          count_over_time({job="varlogs"} |= "status" [10m]) 
            > 0
        for: 1m