# docker-compose
# author: dreamlu
# github.com/dreamlu
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
    networks:
      - demo
  nsqd:
    image: nsqio/nsq:v1.2.1
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -data-path=/data --mem-queue-size=0 # 记录和持久存储
    #    depends_on:
    #      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
    networks:
      - demo
    # 如需持久化
    volumes:
      - /root/txgc/bak/nsq/data:/data
  nsqadmin:
    image: nsqio/nsq:v1.2.1
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    #    depends_on:
    #      - nsqlookupd
    ports:
      - 4171:4171
    networks:
      - demo

networks:
  demo:
    driver: bridge